
FROM node:21-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
ENV CI=true
RUN corepack enable

FROM base AS build
COPY . /usr/src/app
WORKDIR /usr/src/app

RUN pnpm install --frozen-lockfile

RUN pnpm \
    --filter @packages/shared \
    --filter lh-cs-be \
    build

FROM base AS production
COPY --from=build /usr/src/app/apps/api/lh-cs-be /prod/apps/api/lh-cs-be
COPY --from=build /usr/src/app/configs /prod/configs
COPY --from=build /usr/src/app/packages /prod/packages
COPY --from=build /usr/src/app/node_modules /prod/node_modules
COPY --from=build /usr/src/app/package.json /prod

WORKDIR /prod

EXPOSE 8080
CMD ["pnpm","--filter=lh-cs-be", "start:prod"]
