INSERT INTO lh_cs__facilities (
    facility_id,
    title, 
    description, 
    type
) VALUES 
(1,'실외기실 루버창', '시설 설명', 'CONSTRUCTION'),
(2,'에어컨 매립배관', '시설 설명', 'CONSTRUCTION'),
(3,'양변기 로우탱크 내부', '시설 설명', 'CONSTRUCTION'),
(4,'발코니 난간(형상)', '시설 설명', 'CONSTRUCTION'),
(5,'현관문 클로저(형상)', '시설 설명', 'CONSTRUCTION'),
(6,'욕실 점검구(형상)', '시설 설명', 'CONSTRUCTION'),
(7,'가스차단기', '시설 설명', 'MACHINE'),
(8,'온수분배기', '시설 설명', 'MACHINE'),
(9,'환기시스템 등', '시설 설명', 'MACHINE'),
(10,'렌지후드', '시설 설명', 'MACHINE'),
(11,'보일러', '시설 설명', 'MACHINE'),
(12,'터치수전', '시설 설명', 'MACHINE'),
(13,'대피소 피난사다리', '시설 설명', 'MACHINE'),
(14,'스프링 쿨러', '시설 설명', 'MACHINE'),
(15,'수도계량기', '시설 설명', 'MACHINE'),
(16,'가스감지기', '시설 설명', 'MACHINE'),
(17,'음식물 탈수기', '시설 설명', 'MACHINE'),
(18,'절수형 페달', '시설 설명', 'MACHINE'),
(19,'발코니 스프레이건', '시설 설명', 'MACHINE'),
(20,'스마트스위치', '시설 설명', 'ELECTRICITY'),
(21,'IOT 콘센트', '시설 설명', 'ELECTRICITY'),
(22,'자동폐쇄장치', '시설 설명', 'ELECTRICITY'),
(23,'월패드', '시설 설명', 'ELECTRICITY'),
(24,'동체감지기', '시설 설명', 'ELECTRICITY'),
(25,'욕실비상폰 등', '시설 설명', 'ELECTRICITY'),
(26,'층간소음 센서', '시설 설명', 'ELECTRICITY'),
(27,'환기센서', '시설 설명', 'ELECTRICITY'),
(28,'현관문 자석감지기', '시설 설명', 'ELECTRICITY');

