# workflow 이름. GitHub의 Actions 탭에서 이 워크플로우가 이렇게 보인다.
name: Build and Deploy to S3

on: #언제 이 workflow가 실행될지를 정의. 하위의 브랜치/경로 필터 조건이 전부 맞아야 실행된다.
  push: #git push 발생 시 on 실행.
    branches: #그 중에서도 정의한 브랜치의 push가 발생했을때만 실행.
      - lh-cs/dev
    paths: #변경된 파일이 정의한 경로 하위의 파일들일 경우만 실행.
      - 'apps/web/lh-cs-fe/**'
jobs: #병렬 or 순차로 실행될 여러 작업 단위를 정의.
  build: #'build'라는 작업 단위를 지정한 것.
    runs-on: ubuntu-22.04 #해당 job이 실행될 가상환경(런너)을 지정. 여기서는 Ubuntu 22.04 리눅스 환경에서 실행.
    environment: lh-cs-fe-dev

    strategy:
      matrix:
        node-version: [20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build common resources
        run: pnpm run preinstall

      - name: Create .env.dev file
        run: |
          echo "VITE_TOUR_CDN_URL=${{ vars.VITE_TOUR_CDN_URL }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_WS_URL=${{ vars.VITE_WS_URL }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_BASE_URL=${{ vars.VITE_BASE_URL }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_SELF_URL=${{ vars.VITE_SELF_URL }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_VISION_AI_CHILD_PATH=${{ vars.VITE_VISION_AI_CHILD_PATH }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_IS_PREFER_CURRENT_TAB=${{ vars.VITE_IS_PREFER_CURRENT_TAB }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_CONSULTATION_MAX_ROOM_COUNT=${{ vars.VITE_CONSULTATION_MAX_ROOM_COUNT }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_MAX_FILE_UPLOAD_SIZE_MB=${{ vars.VITE_MAX_FILE_UPLOAD_SIZE_MB }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_WEBRTC_SERVER_IP=${{ secrets.VITE_WEBRTC_SERVER_IP }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_WEBRTC_SERVER_USERNAME=${{ secrets.VITE_WEBRTC_SERVER_USERNAME }}" >> ./apps/web/lh-cs-fe/.env.dev
          echo "VITE_WEBRTC_SERVER_CREDENTIAL=${{ secrets.VITE_WEBRTC_SERVER_CREDENTIAL }}" >> ./apps/web/lh-cs-fe/.env.dev
          cat ./apps/web/lh-cs-fe/.env.dev

      - name: Build project
        run: pnpm run --filter lh-cs-fe build:dev

      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_DEV_ELYPECS_SOLUTION_BUCKET }}/lh-cs-fe
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: './apps/web/lh-cs-fe/dist'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
